name: Gradle Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Cache gradle installation for gradle wrapper
      uses: actions/cache@v1
      with:
        key: gradle-installation
        path: ./.gradle
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with gradle wrapper
      run: ./gradlew build
